### ISSUE TITLE
TypeError on Thumbnails API & Conversion

### ISSUE THREAD

**Issue by epaitoo** [cloudconvert/cloudconvert-laravel#10]
I was trying out the Thumbnails API on cloudconvert and I was getting an error of:  `TypeError: array_intersect_key(): Argument #1 ($array) must be of type array, null given in file C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Collections\Arr.php on line 405`. 

I figured maybe there's something wrong with my code so I tried the code to upload, convert and download a file to verify but I was getting the same error.

Please this is the code:
```
 $job = (new Job())
        ->addTask(new Task('import/upload', 'upload-my-file'))
        ->addTask(
            (new Task('convert', 'convert-my-file'))
                ->set('input', 'upload-my-file')
                ->set('output_format', 'html')
        )
        ->addTask(
            (new Task('export/url', 'export-my-file'))
                ->set('input', 'convert-my-file')
        );


        CloudConvert::jobs()->create($job);

        $uploadTask = $job->getTasks()->name('upload-my-file')[0];
        $inputStream = fopen($this->sourcePath, 'r');

        CloudConvert::tasks()->upload($uploadTask, $inputStream);

        CloudConvert::jobs()->wait($job);

        foreach ($job->getExportUrls() as $file) {
            $source = $cloudconvert->getHttpTransport()->download($file->url)->detach();
            $dest = fopen(Storage::path('out/' . $file->filename), 'w');
            
            stream_copy_to_stream($source, $dest);
        }

```

This is also the Thumbnails Task code:

```
 $job = (new Job())
        ->addTask(new Task('import/url', 'import-my-file'))
                ->set('url', 'http://www.africau.edu/images/default/sample.pdf')
        ->addTask(
            (new Task('thumbnail', 'create-book-thumbnail'))
                ->set('input', 'import-my-file')
                ->set('output_format', 'png')
               ->set('filename', 'book-thumbnail.png')
        )
        ->addTask(
            (new Task('export/url', 'export-my-file'))
                ->set('input', 'convert-my-file')
        );


        CloudConvert::jobs()->create($job);


        CloudConvert::jobs()->wait($job);

        foreach ($job->getExportUrls() as $file) {
            $source = $cloudconvert->getHttpTransport()->download($file->url)->detach();
            $dest = fopen(Storage::path('out/' . $file->filename), 'w');
            
            stream_copy_to_stream($source, $dest);
        }
```

Please this the full stack trace: 

```

TypeError: array_intersect_key(): Argument #1 ($array) must be of type array, null given in file C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Collections\Arr.php on line 405

#0 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(405): array_intersect_key()
#1 C:\xampp\htdocs\ytakenotesapp-api\vendor\cloudconvert\cloudconvert-laravel\src\Providers\CloudConvertServiceProvider.php(40): Illuminate\Support\Arr::only()
#2 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Container\Container.php(869): CloudConvert\Laravel\Providers\CloudConvertServiceProvider-&gt;CloudConvert\Laravel\Providers\{closure}()
#3 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Container\Container.php(754): Illuminate\Container\Container-&gt;build()
#4 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(841): Illuminate\Container\Container-&gt;resolve()
#5 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Container\Container.php(692): Illuminate\Foundation\Application-&gt;resolve()
#6 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(826): Illuminate\Container\Container-&gt;make()
#7 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Container\Container.php(1418): Illuminate\Foundation\Application-&gt;make()
#8 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Container\Container-&gt;offsetGet()
#9 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#10 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(255): Illuminate\Support\Facades\Facade::getFacadeRoot()
#11 C:\xampp\htdocs\ytakenotesapp-api\app\Http\Controllers\FileConversionController.php(348): Illuminate\Support\Facades\Facade::__callStatic()
#12 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\FileConversionController-&gt;testCloudConvert()
#13 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction()
#14 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(254): Illuminate\Routing\ControllerDispatcher-&gt;dispatch()
#15 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(197): Illuminate\Routing\Route-&gt;runController()
#16 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Route-&gt;run()
#17 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#18 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#19 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle()
#20 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#21 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(103): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest()
#22 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter()
#23 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle()
#24 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#25 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline-&gt;then()
#26 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#27 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router-&gt;runRoute()
#28 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router-&gt;dispatchToRoute()
#29 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(166): Illuminate\Routing\Router-&gt;dispatch()
#30 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#31 C:\xampp\htdocs\ytakenotesapp-api\vendor\sentry\sentry-laravel\src\Sentry\Laravel\Http\SetRequestIpMiddleware.php(55): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#32 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Sentry\Laravel\Http\SetRequestIpMiddleware-&gt;handle()
#33 C:\xampp\htdocs\ytakenotesapp-api\vendor\sentry\sentry-laravel\src\Sentry\Laravel\Http\SetRequestMiddleware.php(52): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#34 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Sentry\Laravel\Http\SetRequestMiddleware-&gt;handle()
#35 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#36 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#37 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle()
#38 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#39 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#40 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle()
#41 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#42 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#43 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#44 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#45 C:\xampp\htdocs\ytakenotesapp-api\vendor\fruitcake\laravel-cors\src\HandleCors.php(52): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#46 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle()
#47 C:\xampp\htdocs\ytakenotesapp-api\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#48 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle()
#49 C:\xampp\htdocs\ytakenotesapp-api\vendor\sentry\sentry-laravel\src\Sentry\Laravel\Tracing\Middleware.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#50 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Sentry\Laravel\Tracing\Middleware-&gt;handle()
#51 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#52 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(141): Illuminate\Pipeline\Pipeline-&gt;then()
#53 C:\xampp\htdocs\ytakenotesapp-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#54 C:\xampp\htdocs\ytakenotesapp-api\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#55 C:\xampp\htdocs\ytakenotesapp-api\server.php(21): require_once('...')
#56 {main}

```

**Comment by josiasmontag** [comment]
Most probably you did not publish the config or did not flush the config cache.

**Comment by epaitoo** [comment]
Yeah I probably didn't flush the config cache. I will do that and reply ASAP with the results.

**Comment by epaitoo** [comment]
@josiasmontag flushed it and it worked. Thanks!
