### ISSUE TITLE
Cant upload, getting First argument to Stream::create() must be a string, resource or StreamInterface.

### ISSUE THREAD

**Issue by luisjimenez6245** [cloudconvert/cloudconvert-laravel#3]
Im getting this error, caused by the HttplugFactory, can't receive numbers but it is receiving one. 

```
InvalidArgumentException: First argument to Stream::create() must be a string, resource or StreamInterface. in file /var/www/vendor/nyholm/psr7/src/Stream.php on line 87

#0 /var/www/vendor/nyholm/psr7/src/Factory/HttplugFactory.php(29): Nyholm\Psr7\Stream::create(1595857420)
#1 /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php(320): Nyholm\Psr7\Factory\HttplugFactory->createStream(1595857420)
#2 /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php(90): Http\Message\MultipartStream\MultipartStreamBuilder->createStream(1595857420)
#3 /var/www/vendor/cloudconvert/cloudconvert-php/src/Transport/HttpTransport.php(188): Http\Message\MultipartStream\MultipartStreamBuilder->addResource('expires', 1595857420)
#4 /var/www/vendor/cloudconvert/cloudconvert-php/src/Resources/TasksResource.php(111): CloudConvert\Transport\HttpTransport->upload('https://storage...', Resource id #860, Array)
```

**Comment by josiasmontag** [comment]
What exactly are you passing to `CloudConvert::tasks()->upload()`?  Please check if it is a valid stream.

**Comment by luisjimenez6245** [comment]
Actually I'm trying to upload a file directly from my request. 
```

 $file = $request->file;
        $file_path = $file->getRealPath();

        $job = (new Job())
            ->addTask(new Task('import/upload', 'import-1'))
            ->addTask(
                (new Task('convert', 'task-1'))
                    ->set('output_format', 'tar.bz2')
                    ->set('input', ["import-1"])
            )
            ->addTask(
                (new Task('export/url', 'export-1'))
                    ->set('input', ["task-1"])
                    ->set('archive_multiple_files', false)
            );

        CloudConvert::jobs()->create($job);
        $uploadTask = $job->getTasks()->name('import-1')[0];
        $inputStream = fopen(Storage::path($file_path), 'r');

       CloudConvert::tasks()->upload($uploadTask, $inputStream);

```

**Comment by luisjimenez6245** [comment]
I tried to put a static file and I have the same error. 
```

<!--
InvalidArgumentException: First argument to Stream::create() must be a string, resource or StreamInterface. in file /var/www/vendor/nyholm/psr7/src/Stream.php on line 87

#0 /var/www/vendor/nyholm/psr7/src/Factory/HttplugFactory.php(29): Nyholm\Psr7\Stream::create(1595878455)
#1 /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php(320): Nyholm\Psr7\Factory\HttplugFactory->createStream(1595878455)
#2 /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php(90): Http\Message\MultipartStream\MultipartStreamBuilder->createStream(1595878455)
#3 /var/www/vendor/cloudconvert/cloudconvert-php/src/Transport/HttpTransport.php(188): Http\Message\MultipartStream\MultipartStreamBuilder->addResource('expires', 1595878455)
#4 /var/www/vendor/cloudconvert/cloudconvert-php/src/Resources/TasksResource.php(111): CloudConvert\Transport\HttpTransport->upload('https://storage...', Resource id #15, Array)
#5 /var/www/app/Http/Controllers/UserAccess/GameWorldController.php(52): CloudConvert\Resources\TasksResource->upload(Object(CloudConvert\Models\Task), Resource id #15)
#6 [internal function]: App\Http\Controllers\UserAccess\GameWorldController->store(Object(App\Game), Object(App\Http\Requests\UserAccess\GameWorldRequest))
#7 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#8 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#9 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\UserAccess\GameWorldController), 'store')
#10 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 1000, '1')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Nova\Http\Middleware\ServeNova->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/app/Http/Middleware/Locale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\Locale->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}
-->

````

**Comment by josiasmontag** [comment]
Fixed by https://github.com/cloudconvert/cloudconvert-php/commit/f34eca1b047be018425e4407d25d6d61719201b6 / cloudconvert-php `3.0.6`
